#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace YokiFrame
{
    /// <summary>
    /// 默认 UI 代码生成模板 - YokiFrame 标准样式
    /// 继承此类可自定义代码生成样式，只需覆盖需要修改的方法
    /// </summary>
    public partial class DefaultUICodeGenTemplate : IUICodeGenTemplate
    {
        public virtual string TemplateName => UICodeGenTemplateRegistry.DEFAULT_TEMPLATE_NAME;
        public virtual string Description => "YokiFrame 默认代码生成样式";

        #region IUICodeGenTemplate 实现

        public virtual void WritePanel(UICodeGenContext context)
        {
            var filePath = context.GetPanelFilePath();
            if (File.Exists(filePath)) return;

            var options = context.Options ?? new PanelCodeGenOptions();
            var dataName = $"{context.PanelName}Data";

            var root = new RootCode();
            root.Using(UICodeGenConstants.USING_UNITY_ENGINE)
                .Using(UICodeGenConstants.USING_UNITY_UI)
                .Using(UICodeGenConstants.USING_YOKI_FRAME)
                .EmptyLine()
                .Namespace(context.ScriptNamespace, ns =>
                {
                    // 数据类
                    ns.Class(dataName, nameof(IUIData), false, false, _ => { });

                    // 面板类
                    ns.Class(context.PanelName, nameof(UIPanel), true, false, cls =>
                    {
                        WritePanelLifecycleMethods(cls, dataName);

                        if (options.GenerateLifecycleHooks)
                        {
                            WritePanelLifecycleHooks(cls);
                        }

                        if (options.GenerateFocusSupport)
                        {
                            WritePanelFocusSupport(cls);
                        }
                    });
                });

            WriteToFile(filePath, root);
        }

        public virtual void WritePanelDesigner(UICodeGenContext context)
        {
            var filePath = context.GetPanelDesignerPath();

            var root = new RootCode();
            WriteAutoGeneratedHeader(root);
            root.Using(UICodeGenConstants.USING_SYSTEM)
                .Using(UICodeGenConstants.USING_UNITY_ENGINE)
                .Using(UICodeGenConstants.USING_UNITY_UI)
                .Using(UICodeGenConstants.USING_YOKI_FRAME)
                .EmptyLine()
                .Namespace(context.ScriptNamespace, ns =>
                {
                    ns.Custom($"// Generate Id:{Guid.NewGuid()}");
                    ns.Class(context.PanelName, string.Empty, true, false, cls =>
                    {
                        // 生成绑定字段
                        WriteBindFields(cls, context.BindCodeInfo, context);

                        cls.EmptyLine();

                        // 生成 ClearUIComponents 方法
                        WriteClearMethod(cls, context.BindCodeInfo, "ClearUIComponents", true);

                        cls.EmptyLine();

                        // 生成 Data 属性
                        WriteDataProperty(cls, context.PanelName);
                    });
                });

            WriteToFile(filePath, root);
        }

        public virtual void WriteBindTypeUserFile(UICodeGenContext context, BindCodeInfo bindInfo, IBindTypeStrategy strategy)
        {
            var scriptPath = strategy.GetScriptPath(bindInfo, context, false);
            if (string.IsNullOrEmpty(scriptPath) || File.Exists(scriptPath)) return;

            Directory.CreateDirectory(PathUtils.GetDirectoryPath(scriptPath));

            var typeNamespace = strategy.GetNamespace(context);
            var baseClassName = strategy.GetBaseClassName();

            var root = new RootCode();
            WriteUserFileHeader(root);
            root.Using(UICodeGenConstants.USING_UNITY_ENGINE)
                .Using(UICodeGenConstants.USING_UNITY_UI)
                .Using(UICodeGenConstants.USING_YOKI_FRAME)
                .EmptyLine()
                .Namespace(typeNamespace, ns =>
                {
                    ns.Class(bindInfo.Type, baseClassName, true, false, _ => { });
                });

            WriteToFile(scriptPath, root);
        }

        public virtual void WriteBindTypeDesignerFile(UICodeGenContext context, BindCodeInfo bindInfo, IBindTypeStrategy strategy)
        {
            var scriptPath = strategy.GetScriptPath(bindInfo, context, true);
            if (string.IsNullOrEmpty(scriptPath)) return;

            Directory.CreateDirectory(PathUtils.GetDirectoryPath(scriptPath));

            // Component 下过滤 Element
            if (bindInfo.Bind == BindType.Component)
            {
                FilterElementsFromComponent(bindInfo);
            }

            var typeNamespace = strategy.GetNamespace(context);
            var isComponent = bindInfo.Bind == BindType.Component;

            var root = new RootCode();
            WriteAutoGeneratedHeader(root);
            root.Using(UICodeGenConstants.USING_UNITY_ENGINE)
                .Using(UICodeGenConstants.USING_UNITY_UI)
                .Using(UICodeGenConstants.USING_YOKI_FRAME)
                .EmptyLine()
                .Namespace(typeNamespace, ns =>
                {
                    ns.Class(bindInfo.Type, string.Empty, true, false, cls =>
                    {
                        WriteBindFieldsForDesigner(cls, bindInfo, context, isComponent);
                        cls.EmptyLine();
                        WriteClearMethod(cls, bindInfo, "Clear", false);
                    });
                });

            WriteToFile(scriptPath, root);
        }

        public virtual void WriteBindTypeCode(BindCodeInfo bindInfo, UICodeGenContext context)
        {
            if (bindInfo.RepeatElement) return;

            var strategy = BindStrategyRegistry.Get(bindInfo.Bind);
            if (strategy == null || !strategy.RequiresClassFile) return;

            // 检查是否已生成
            if (!context.MarkTypeGenerated(bindInfo.Bind, bindInfo.Type)) return;

            // 生成用户文件和 Designer 文件
            WriteBindTypeUserFile(context, bindInfo, strategy);
            WriteBindTypeDesignerFile(context, bindInfo, strategy);
        }

        #endregion

        #region 文件头生成

        /// <summary>
        /// 写入自动生成文件头
        /// </summary>
        protected virtual void WriteAutoGeneratedHeader(RootCode rootCode)
        {
            var timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            rootCode
                .Custom("//------------------------------------------------------------------------------")
                .Custom("// <auto-generated>")
                .Custom("//     This code was generated by YokiFrame UIKit.")
                .Custom($"//     Generated at: {timestamp}")
                .Custom("//")
                .Custom("//     Changes to this file may cause incorrect behavior and will be lost if")
                .Custom("//     the code is regenerated.")
                .Custom("// </auto-generated>")
                .Custom("//------------------------------------------------------------------------------")
                .EmptyLine();
        }

        /// <summary>
        /// 写入用户文件头
        /// </summary>
        protected virtual void WriteUserFileHeader(RootCode rootCode)
        {
            rootCode
                .Custom("/****************************************************************************")
                .Custom($"{DateTime.Now.Year}.{DateTime.Now.Month} {SystemInfo.deviceName}")
                .Custom("****************************************************************************/")
                .EmptyLine();
        }

        #endregion

        #region 工具方法

        /// <summary>
        /// 写入文件
        /// </summary>
        protected void WriteToFile(string filePath, RootCode root)
        {
            Directory.CreateDirectory(PathUtils.GetDirectoryPath(filePath));
            using var writer = File.CreateText(filePath);
            var codeWriter = new FileCodeWriteKit(writer);
            root.Gen(codeWriter);
        }

        /// <summary>
        /// 过滤 Component 中的 Element
        /// </summary>
        protected void FilterElementsFromComponent(BindCodeInfo bindCodeInfo)
        {
            var keysToRemove = new List<string>(4);

            foreach (var kvp in bindCodeInfo.MemberDic)
            {
                if (kvp.Value.Bind is BindType.Element)
                {
                    keysToRemove.Add(kvp.Key);
                }
            }

            foreach (var key in keysToRemove)
            {
                bindCodeInfo.MemberDic.Remove(key);
            }
        }

        #endregion
    }
}
#endif
