
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.exgas
{
public sealed partial class abilityGameCore : Luban.BeanBase
{
    public abilityGameCore(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["PrefabGuid"].IsString) { throw new SerializationException(); }  PrefabGuid = _buf["PrefabGuid"]; }
        { if(!_buf["PrefabPath"].IsString) { throw new SerializationException(); }  PrefabPath = _buf["PrefabPath"]; }
        { if(!_buf["IconGuid"].IsString) { throw new SerializationException(); }  IconGuid = _buf["IconGuid"]; }
        { if(!_buf["IconPath"].IsString) { throw new SerializationException(); }  IconPath = _buf["IconPath"]; }
        { if(!_buf["AbilityRootMode"].IsNumber) { throw new SerializationException(); }  AbilityRootMode = _buf["AbilityRootMode"]; }
        { if(!_buf["InputTriggerMode"].IsNumber) { throw new SerializationException(); }  InputTriggerMode = _buf["InputTriggerMode"]; }
        { if(!_buf["BufferInput"].IsBoolean) { throw new SerializationException(); }  BufferInput = _buf["BufferInput"]; }
        { if(!_buf["NewInputExtendsBuffer"].IsBoolean) { throw new SerializationException(); }  NewInputExtendsBuffer = _buf["NewInputExtendsBuffer"]; }
        { if(!_buf["MaximumBufferDuration"].IsNumber) { throw new SerializationException(); }  MaximumBufferDuration = _buf["MaximumBufferDuration"]; }
        { if(!_buf["DelayBeforeUseReleaseInterruption"].IsBoolean) { throw new SerializationException(); }  DelayBeforeUseReleaseInterruption = _buf["DelayBeforeUseReleaseInterruption"]; }
        { if(!_buf["TimeBetweenUsesReleaseInterruption"].IsBoolean) { throw new SerializationException(); }  TimeBetweenUsesReleaseInterruption = _buf["TimeBetweenUsesReleaseInterruption"]; }
        { if(!_buf["UpdateLookAtDirectionOnFire"].IsBoolean) { throw new SerializationException(); }  UpdateLookAtDirectionOnFire = _buf["UpdateLookAtDirectionOnFire"]; }
    }

    public static abilityGameCore DeserializeabilityGameCore(JSONNode _buf)
    {
        return new exgas.abilityGameCore(_buf);
    }

    /// <summary>
    /// EX-GAS Ability ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// GameCore PrefabReference database GUID
    /// </summary>
    public readonly string PrefabGuid;
    /// <summary>
    /// Optional ResourceSystem/Addressables runtime address; empty when PrefabGuid resolves through DatabaseRegistry
    /// </summary>
    public readonly string PrefabPath;
    /// <summary>
    /// GameCore SpriteReference database GUID
    /// </summary>
    public readonly string IconGuid;
    /// <summary>
    /// Optional ResourceSystem/Addressables runtime address; empty when IconGuid resolves through DatabaseRegistry
    /// </summary>
    public readonly string IconPath;
    /// <summary>
    /// 0 Static / 1 Polydirectional / 2 Horizontal
    /// </summary>
    public readonly int AbilityRootMode;
    /// <summary>
    /// 0 SemiAuto / 1 Auto
    /// </summary>
    public readonly int InputTriggerMode;
    /// <summary>
    /// Buffer input while busy
    /// </summary>
    public readonly bool BufferInput;
    /// <summary>
    /// New input refreshes buffer
    /// </summary>
    public readonly bool NewInputExtendsBuffer;
    /// <summary>
    /// Input buffer seconds
    /// </summary>
    public readonly float MaximumBufferDuration;
    /// <summary>
    /// Release cancels during Timeline windup
    /// </summary>
    public readonly bool DelayBeforeUseReleaseInterruption;
    /// <summary>
    /// Release stops during Timeline recovery
    /// </summary>
    public readonly bool TimeBetweenUsesReleaseInterruption;
    /// <summary>
    /// Update look direction when fired
    /// </summary>
    public readonly bool UpdateLookAtDirectionOnFire;
   
    public const int __ID__ = -1827378861;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "PrefabGuid:" + PrefabGuid + ","
        + "PrefabPath:" + PrefabPath + ","
        + "IconGuid:" + IconGuid + ","
        + "IconPath:" + IconPath + ","
        + "AbilityRootMode:" + AbilityRootMode + ","
        + "InputTriggerMode:" + InputTriggerMode + ","
        + "BufferInput:" + BufferInput + ","
        + "NewInputExtendsBuffer:" + NewInputExtendsBuffer + ","
        + "MaximumBufferDuration:" + MaximumBufferDuration + ","
        + "DelayBeforeUseReleaseInterruption:" + DelayBeforeUseReleaseInterruption + ","
        + "TimeBetweenUsesReleaseInterruption:" + TimeBetweenUsesReleaseInterruption + ","
        + "UpdateLookAtDirectionOnFire:" + UpdateLookAtDirectionOnFire + ","
        + "}";
    }
}
}

