
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.exgas
{
public partial class TbabilityGameCore
{
    private readonly System.Collections.Generic.Dictionary<int, exgas.abilityGameCore> _dataMap;
    private readonly System.Collections.Generic.List<exgas.abilityGameCore> _dataList;
    
    public TbabilityGameCore(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, exgas.abilityGameCore>();
        _dataList = new System.Collections.Generic.List<exgas.abilityGameCore>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            exgas.abilityGameCore _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.exgas.abilityGameCore.DeserializeabilityGameCore(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, exgas.abilityGameCore> DataMap => _dataMap;
    public System.Collections.Generic.List<exgas.abilityGameCore> DataList => _dataList;

    public exgas.abilityGameCore GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public exgas.abilityGameCore Get(int key) => _dataMap[key];
    public exgas.abilityGameCore this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

