
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// Ability逻辑基类
/// </summary>
public abstract partial class AbilityLogicBase : Luban.BeanBase
{
    public AbilityLogicBase(JSONNode _buf) 
    {
    }

    public static AbilityLogicBase DeserializeAbilityLogicBase(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "ALApplyEffect": return new ALApplyEffect(_buf);
            case "ALDebugLog": return new ALDebugLog(_buf);
            case "ALTimeline": return new ALTimeline(_buf);
            case "FormalAbilityRuleProxyLogic": return new FormalAbilityRuleProxyLogic(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

