
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// TargetCatcher: CatchAreaCircle2D
/// </summary>
public sealed partial class CatchAreaCircle2D : TargetCatcherBase
{
    public CatchAreaCircle2D(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Param"].IsObject) { throw new SerializationException(); }  Param = global::cfg.XParamCatchAreaCircle2D.DeserializeXParamCatchAreaCircle2D(_buf["Param"]);  }
    }

    public static CatchAreaCircle2D DeserializeCatchAreaCircle2D(JSONNode _buf)
    {
        return new CatchAreaCircle2D(_buf);
    }

    /// <summary>
    /// 参数
    /// </summary>
    public readonly XParamCatchAreaCircle2D Param;
   
    public const int __ID__ = 93022474;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Param?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Param:" + Param + ","
        + "}";
    }
}
}

