
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// Cue: CuePlayGameCoreFeedback
/// </summary>
public sealed partial class CuePlayGameCoreFeedback : GameplayCueBase
{
    public CuePlayGameCoreFeedback(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Param"].IsObject) { throw new SerializationException(); }  Param = global::cfg.XParamGameCoreFeedback.DeserializeXParamGameCoreFeedback(_buf["Param"]);  }
    }

    public static CuePlayGameCoreFeedback DeserializeCuePlayGameCoreFeedback(JSONNode _buf)
    {
        return new CuePlayGameCoreFeedback(_buf);
    }

    /// <summary>
    /// 参数
    /// </summary>
    public readonly XParamGameCoreFeedback Param;
   
    public const int __ID__ = 1408996189;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Param?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Param:" + Param + ","
        + "}";
    }
}
}

