
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial struct FormalConditionalDamage
{
    public FormalConditionalDamage(JSONNode _buf) 
    {
        { if(!_buf["ConditionKind"].IsNumber) { throw new SerializationException(); }  ConditionKind = _buf["ConditionKind"]; }
        { if(!_buf["FacingDotThreshold"].IsNumber) { throw new SerializationException(); }  FacingDotThreshold = _buf["FacingDotThreshold"]; }
        { if(!_buf["DamageType"].IsNumber) { throw new SerializationException(); }  DamageType = _buf["DamageType"]; }
        { if(!_buf["FlatDamage"].IsNumber) { throw new SerializationException(); }  FlatDamage = _buf["FlatDamage"]; }
        { if(!_buf["ScalingFactor"].IsNumber) { throw new SerializationException(); }  ScalingFactor = _buf["ScalingFactor"]; }
        { if(!_buf["IgnoreDefense"].IsBoolean) { throw new SerializationException(); }  IgnoreDefense = _buf["IgnoreDefense"]; }
        { if(!_buf["VisualFlags"].IsNumber) { throw new SerializationException(); }  VisualFlags = _buf["VisualFlags"]; }
        { if(!_buf["ImpactDataType"].IsNumber) { throw new SerializationException(); }  ImpactDataType = _buf["ImpactDataType"]; }
        { if(!_buf["ImpactData"].IsObject) { throw new SerializationException(); }  ImpactData = global::cfg.vector2.Deserializevector2(_buf["ImpactData"]);  }
        { if(!_buf["PushMode"].IsNumber) { throw new SerializationException(); }  PushMode = _buf["PushMode"]; }
        { if(!_buf["PushIntensity"].IsNumber) { throw new SerializationException(); }  PushIntensity = _buf["PushIntensity"]; }
        { if(!_buf["PushResistance"].IsNumber) { throw new SerializationException(); }  PushResistance = _buf["PushResistance"]; }
        { if(!_buf["InvincibilityDuration"].IsNumber) { throw new SerializationException(); }  InvincibilityDuration = _buf["InvincibilityDuration"]; }
    }

    public static FormalConditionalDamage DeserializeFormalConditionalDamage(JSONNode _buf)
    {
        return new FormalConditionalDamage(_buf);
    }

    public readonly int ConditionKind;
    public readonly float FacingDotThreshold;
    public readonly int DamageType;
    public readonly int FlatDamage;
    public readonly float ScalingFactor;
    public readonly bool IgnoreDefense;
    public readonly int VisualFlags;
    public readonly int ImpactDataType;
    public readonly vector2 ImpactData;
    public readonly int PushMode;
    public readonly float PushIntensity;
    public readonly float PushResistance;
    public readonly float InvincibilityDuration;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ConditionKind:" + ConditionKind + ","
        + "FacingDotThreshold:" + FacingDotThreshold + ","
        + "DamageType:" + DamageType + ","
        + "FlatDamage:" + FlatDamage + ","
        + "ScalingFactor:" + ScalingFactor + ","
        + "IgnoreDefense:" + IgnoreDefense + ","
        + "VisualFlags:" + VisualFlags + ","
        + "ImpactDataType:" + ImpactDataType + ","
        + "ImpactData:" + ImpactData + ","
        + "PushMode:" + PushMode + ","
        + "PushIntensity:" + PushIntensity + ","
        + "PushResistance:" + PushResistance + ","
        + "InvincibilityDuration:" + InvincibilityDuration + ","
        + "}";
    }
}
}

