
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// Task: TaskApplyWorldElement
/// </summary>
public sealed partial class TaskApplyWorldElement : AbilityTaskBase
{
    public TaskApplyWorldElement(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Param"].IsObject) { throw new SerializationException(); }  Param = global::cfg.XParamApplyWorldElement.DeserializeXParamApplyWorldElement(_buf["Param"]);  }
    }

    public static TaskApplyWorldElement DeserializeTaskApplyWorldElement(JSONNode _buf)
    {
        return new TaskApplyWorldElement(_buf);
    }

    /// <summary>
    /// 参数
    /// </summary>
    public readonly XParamApplyWorldElement Param;
   
    public const int __ID__ = 161704563;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Param?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Param:" + Param + ","
        + "}";
    }
}
}

