
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 参数类型: XParamGameCoreFeedback
/// </summary>
public sealed partial class XParamGameCoreFeedback : XParam
{
    public XParamGameCoreFeedback(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Kind"].IsNumber) { throw new SerializationException(); }  Kind = _buf["Kind"]; }
        { if(!_buf["Target"].IsNumber) { throw new SerializationException(); }  Target = _buf["Target"]; }
    }

    public static XParamGameCoreFeedback DeserializeXParamGameCoreFeedback(JSONNode _buf)
    {
        return new XParamGameCoreFeedback(_buf);
    }

    /// <summary>
    /// GameCore反馈事件
    /// </summary>
    public readonly int Kind;
    /// <summary>
    /// GameCore反馈目标
    /// </summary>
    public readonly int Target;
   
    public const int __ID__ = 253054603;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Kind:" + Kind + ","
        + "Target:" + Target + ","
        + "}";
    }
}
}

