
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 参数类型: XParamApplyWorldElement
/// </summary>
public sealed partial class XParamApplyWorldElement : XParam
{
    public XParamApplyWorldElement(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["ElementKind"].IsNumber) { throw new SerializationException(); }  ElementKind = _buf["ElementKind"]; }
        { if(!_buf["Intensity"].IsNumber) { throw new SerializationException(); }  Intensity = _buf["Intensity"]; }
        { if(!_buf["ExposureDuration"].IsNumber) { throw new SerializationException(); }  ExposureDuration = _buf["ExposureDuration"]; }
        { if(!_buf["IntervalFrames"].IsNumber) { throw new SerializationException(); }  IntervalFrames = _buf["IntervalFrames"]; }
        { if(!_buf["ConeRange"].IsNumber) { throw new SerializationException(); }  ConeRange = _buf["ConeRange"]; }
        { if(!_buf["ConeHalfAngleDegrees"].IsNumber) { throw new SerializationException(); }  ConeHalfAngleDegrees = _buf["ConeHalfAngleDegrees"]; }
    }

    public static XParamApplyWorldElement DeserializeXParamApplyWorldElement(JSONNode _buf)
    {
        return new XParamApplyWorldElement(_buf);
    }

    /// <summary>
    /// 世界元素类型
    /// </summary>
    public readonly int ElementKind;
    /// <summary>
    /// 元素强度
    /// </summary>
    public readonly float Intensity;
    /// <summary>
    /// 单次元素暴露时长
    /// </summary>
    public readonly float ExposureDuration;
    /// <summary>
    /// 持续片段重复提交间隔帧
    /// </summary>
    public readonly int IntervalFrames;
    /// <summary>
    /// 锥形世界距离
    /// </summary>
    public readonly float ConeRange;
    /// <summary>
    /// 锥形半角（度）
    /// </summary>
    public readonly float ConeHalfAngleDegrees;
   
    public const int __ID__ = -1389952253;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ElementKind:" + ElementKind + ","
        + "Intensity:" + Intensity + ","
        + "ExposureDuration:" + ExposureDuration + ","
        + "IntervalFrames:" + IntervalFrames + ","
        + "ConeRange:" + ConeRange + ","
        + "ConeHalfAngleDegrees:" + ConeHalfAngleDegrees + ","
        + "}";
    }
}
}

