
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 参数类型: XParamCatchAreaBox2D
/// </summary>
public sealed partial class XParamCatchAreaBox2D : XParam
{
    public XParamCatchAreaBox2D(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["isWorldSpace"].IsBoolean) { throw new SerializationException(); }  IsWorldSpace = _buf["isWorldSpace"]; }
        { if(!_buf["offset"].IsObject) { throw new SerializationException(); }  Offset = global::cfg.vector2.Deserializevector2(_buf["offset"]);  }
        { if(!_buf["size"].IsObject) { throw new SerializationException(); }  Size = global::cfg.vector2.Deserializevector2(_buf["size"]);  }
        { if(!_buf["rotation"].IsNumber) { throw new SerializationException(); }  Rotation = _buf["rotation"]; }
        { if(!_buf["layer"].IsNumber) { throw new SerializationException(); }  Layer = _buf["layer"]; }
    }

    public static XParamCatchAreaBox2D DeserializeXParamCatchAreaBox2D(JSONNode _buf)
    {
        return new XParamCatchAreaBox2D(_buf);
    }

    /// <summary>
    /// isWorldSpace
    /// </summary>
    public readonly bool IsWorldSpace;
    /// <summary>
    /// offset
    /// </summary>
    public readonly vector2 Offset;
    /// <summary>
    /// size
    /// </summary>
    public readonly vector2 Size;
    /// <summary>
    /// rotation
    /// </summary>
    public readonly float Rotation;
    /// <summary>
    /// layer
    /// </summary>
    public readonly int Layer;
   
    public const int __ID__ = 1103905482;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "isWorldSpace:" + IsWorldSpace + ","
        + "offset:" + Offset + ","
        + "size:" + Size + ","
        + "rotation:" + Rotation + ","
        + "layer:" + Layer + ","
        + "}";
    }
}
}

