
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 参数类型: XParamCatchAreaPolygon2D
/// </summary>
public sealed partial class XParamCatchAreaPolygon2D : XParam
{
    public XParamCatchAreaPolygon2D(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["isWorldSpace"].IsBoolean) { throw new SerializationException(); }  IsWorldSpace = _buf["isWorldSpace"]; }
        { if(!_buf["points"].IsString) { throw new SerializationException(); }  Points = _buf["points"]; }
        { if(!_buf["layer"].IsNumber) { throw new SerializationException(); }  Layer = _buf["layer"]; }
    }

    public static XParamCatchAreaPolygon2D DeserializeXParamCatchAreaPolygon2D(JSONNode _buf)
    {
        return new XParamCatchAreaPolygon2D(_buf);
    }

    /// <summary>
    /// isWorldSpace
    /// </summary>
    public readonly bool IsWorldSpace;
    /// <summary>
    /// points
    /// </summary>
    public readonly string Points;
    /// <summary>
    /// layer
    /// </summary>
    public readonly int Layer;
   
    public const int __ID__ = 1161198585;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "isWorldSpace:" + IsWorldSpace + ","
        + "points:" + Points + ","
        + "layer:" + Layer + ","
        + "}";
    }
}
}

