
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 参数类型: XParamGameCoreAudio
/// </summary>
public sealed partial class XParamGameCoreAudio : XParam
{
    public XParamGameCoreAudio(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["AudioResolverGuid"].IsString) { throw new SerializationException(); }  AudioResolverGuid = _buf["AudioResolverGuid"]; }
    }

    public static XParamGameCoreAudio DeserializeXParamGameCoreAudio(JSONNode _buf)
    {
        return new XParamGameCoreAudio(_buf);
    }

    /// <summary>
    /// GameCore音频资源GUID
    /// </summary>
    public readonly string AudioResolverGuid;
   
    public const int __ID__ = 1229096592;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "AudioResolverGuid:" + AudioResolverGuid + ","
        + "}";
    }
}
}

