
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 参数类型: XParamCatchAreaCircle2D
/// </summary>
public sealed partial class XParamCatchAreaCircle2D : XParam
{
    public XParamCatchAreaCircle2D(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["isWorldSpace"].IsBoolean) { throw new SerializationException(); }  IsWorldSpace = _buf["isWorldSpace"]; }
        { if(!_buf["offset"].IsObject) { throw new SerializationException(); }  Offset = global::cfg.vector2.Deserializevector2(_buf["offset"]);  }
        { if(!_buf["radius"].IsNumber) { throw new SerializationException(); }  Radius = _buf["radius"]; }
        { if(!_buf["layer"].IsNumber) { throw new SerializationException(); }  Layer = _buf["layer"]; }
    }

    public static XParamCatchAreaCircle2D DeserializeXParamCatchAreaCircle2D(JSONNode _buf)
    {
        return new XParamCatchAreaCircle2D(_buf);
    }

    /// <summary>
    /// isWorldSpace
    /// </summary>
    public readonly bool IsWorldSpace;
    /// <summary>
    /// offset
    /// </summary>
    public readonly vector2 Offset;
    /// <summary>
    /// radius
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// layer
    /// </summary>
    public readonly int Layer;
   
    public const int __ID__ = 471152277;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "isWorldSpace:" + IsWorldSpace + ","
        + "offset:" + Offset + ","
        + "radius:" + Radius + ","
        + "layer:" + Layer + ","
        + "}";
    }
}
}

