using System;
using System.Linq;

namespace YokiFrame
{
    /// <summary>
    /// 极简 UI 代码生成模板示例 - 展示如何自定义代码生成样式
    /// 
    /// 使用方法：
    /// 1. 创建一个类继承 DefaultUICodeGenTemplate
    /// 2. 系统会自动发现并注册你的模板
    /// 3. 调用 UICodeGenTemplateRegistry.SetActiveTemplate("模板名") 切换模板
    /// </summary>
    public class MinimalUICodeGenTemplate : DefaultUICodeGenTemplate
    {
        public override string TemplateName => "Minimal";
        public override string Description => "极简代码生成样式 - 无注释、无生命周期钩子";

        /// <summary>
        /// 覆盖用户文件头 - 使用更简洁的样式
        /// </summary>
        protected override void WriteUserFileHeader(RootCode rootCode)
        {
            rootCode
                .Custom($"// {DateTime.Now:yyyy-MM-dd}")
                .EmptyLine();
        }

        /// <summary>
        /// 覆盖自动生成文件头 - 使用更简洁的样式
        /// </summary>
        protected override void WriteAutoGeneratedHeader(RootCode rootCode)
        {
            rootCode
                .Custom("// <auto-generated />")
                .EmptyLine();
        }

        /// <summary>
        /// 覆盖 Panel 生命周期方法 - 只生成必要的方法
        /// </summary>
        protected override void WritePanelLifecycleMethods(ClassCodeScope cls, string dataName)
        {
            // 只生成 OnInit 和 OnClose
            cls.ProtectedOverrideVoid("OnInit", method =>
            {
                method.WithParameter(nameof(IUIData), "uiData", "null");
                method.WithBody(body =>
                {
                    body.Custom($"mData = uiData as {dataName} ?? new {dataName}();");
                });
            });
            cls.EmptyLine();

            cls.ProtectedOverrideVoid("OnClose", method =>
            {
                method.WithBody(_ => { });
            });
        }

        /// <summary>
        /// 不生成生命周期钩子
        /// </summary>
        protected override void WritePanelLifecycleHooks(ClassCodeScope cls)
        {
            // 极简模式不生成钩子
        }

        /// <summary>
        /// 不生成焦点支持
        /// </summary>
        protected override void WritePanelFocusSupport(ClassCodeScope cls)
        {
            // 极简模式不生成焦点支持
        }

        /// <summary>
        /// 覆盖 Clear 方法体 - 使用更简洁的实现
        /// </summary>
        protected override void WriteClearMethodBody(ICodeScope body, BindCodeInfo bindCodeInfo, bool clearData)
        {
            // 一行式清理
            foreach (var bindInfo in bindCodeInfo.MemberDic.Values.Where(b => !b.RepeatElement))
            {
                body.Custom($"{bindInfo.Name} = default;");
            }

            if (clearData)
            {
                body.Custom("mData = null;");
            }
        }
    }
}
